version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    stdin_open: true
    tty: true
    ports:
      - "5001:80"
    environment:
      - DEBUG=True
      # Uncomment to enable test credentials mode
      # - MOCK_DATADOG_CLIENT=True
    volumes:
      - ./backend/monitoring/:/app/monitoring
